import Smt
import Smt.Real

/-!
Unsat variant of example 3, NOT one of Li's examples: the last conjunct of the
existential formula is replaced by its complement, which makes it unsatisfiable
with the same polynomials. For comparing the fine-grained and the coarse
reconstruction only.
Generated by `scripts/gen_li_examples.py` from `example_3` in `Univ_RCF_Example.thy`.
-/

set_option maxHeartbeats 4000000 in
lemma li_example_3u (x : Real) :
    ¬((((x * x * x * x * x) - x) - 1) = 0 ∧
      ((((((((((((x * x * x * x * x * x * x * x * x * x * x * x) + ((425 / 23) * (x * x * x * x * x * x * x * x * x * x * x))) - ((228 / 23) * (x * x * x * x * x * x * x * x * x * x))) - (2 * (x * x * x * x * x * x * x * x))) - ((896 / 23) * (x * x * x * x * x * x * x))) - ((394 / 23) * (x * x * x * x * x * x))) + ((456 / 23) * (x * x * x * x * x))) + (x * x * x * x)) + ((471 / 23) * (x * x * x))) + ((645 / 23) * (x * x))) - ((31 / 23) * x)) - (228 / 23)) = 0 ∧
      (((x * x * x) + (22 * (x * x))) - 31) ≥ 0 ∧
      ((((x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x) - ((234 / 567) * (x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x))) - (419 * (x * x * x * x * x * x * x * x * x * x))) + 1948) ≤ 0) := by
  smt

#print axioms li_example_3u
